/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Signable,
  SignableInterface,
} from "../../../contracts/interfaces/Signable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "terms",
        type: "string",
      },
    ],
    name: "AcceptedTerms",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_newtermsUrl",
        type: "string",
      },
    ],
    name: "acceptTerms",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_signer",
        type: "address",
      },
      {
        internalType: "string",
        name: "_newtermsUrl",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "_signature",
        type: "bytes",
      },
    ],
    name: "acceptTermsFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "acceptedTerms",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "termsUrl",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "prefix",
        type: "string",
      },
    ],
    name: "termsUrlWithPrefix",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Signable__factory {
  static readonly abi = _abi;
  static createInterface(): SignableInterface {
    return new utils.Interface(_abi) as SignableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Signable {
    return new Contract(address, _abi, signerOrProvider) as Signable;
  }
}
